;ByHexCode_11_ED6AtoFD61.asm

nnWord	EQU		01234H	; nn 
aByte	EQU		5AH		; n
dByte	EQU		0DDH	; d
;    PC  ->	$

LED6A:	ADC HL, HL
L2A:	LD HL, (nnWord)		; ED 6B lo hi
XED6C:	; NEG*
XED6D:	; RETN*
XED6E:	; IM 0/1*
LED6F:	RLD
XED70:	; IN (C)* / IN F, (C)*
XED71:	; OUT (C), 0*
LED72:	SBC HL, SP
LED73:	LD (nnWord), SP	
XED74:	; NEG*
XED75:	; RETN*
XED76:	; IM 1*
LED78:	IN A, (C)
LED79:	OUT (C), A
LED7A:	ADC HL, SP
LED7B:	LD SP, (nnWord)
XED7C:	; NEG*
XED7D:	; RETN*
XED7E:	; IM 2*
LEDA0:	LDI
LEDA1:	CPI
LEDA2:	INI
LEDA3:	OUTI
LEDA8:	LDD
LEDA9:	CPD
LEDAA:	IND
LEDAB:	OUTD
LEDB0:	LDIR
LEDB1:	CPIR
LEDB2:	INIR
LEDB3:	OTIR
LEDB8:	LDDR
LEDB9:	CPDR
LEDBA:	INDR
LEDBB:	OTDR
LEE:		XOR aByte
LEF:	RST 28h
LF0:	RET P
LF1:	POP AF
LF2:	JP P, nnWord
LF3:	DI
LF4:	CALL P, nnWord
LF5:	PUSH AF
LF6:	OR aByte
LF7:	RST 30h
LF8:	RET M
LF9:	LD SP, HL
LFA:	JP M, nnWord
LFB:	EI
LFC	CALL M, nnWord
LFD09:	ADD IY, BC
LFD19:	ADD IY, DE
LFD21:	LD IY, nnWord
LFD22:	LD (nnWord), IY
LFD23:	INC IY
XFD24:	; INC IYH*
XFD25:	; DEC IYH*
XFD26:	; LD IYH, n*
LFD29:	ADD IY, IY
LFD2A:	LD IY, (nnWord)
LFD2B:	DEC IY
XFD2C:	; INC IYL*
XFD2D:	; DEC IYL*
XFD2E:	; LD IYL, n*
LFD34:	INC (IY + dByte)
LFD35:	DEC (IY + dByte)
LFD36:	LD (IY + dByte), aByte
LFD39:	ADD IY, SP
XFD44:	; LD B, IYH*
XFD45:	; LD B, IYL*
LFD46:	LD B, (IY + dByte)
XFD4C:	; LD C, IYH*
XFD4D:	; LD C, IYL*
LFD4E:	LD C, (IY + dByte)
XFD54:	; LD D, IYH*
XFD55:	; LD D, IYL*
LFD56:	LD D, (IY + dByte)
XFD5C:	; LD E, IYH*
XFD5D:	; LD E, IYL*
LFD5E:	LD E, (IY + dByte)
XFD60:	; LD IYH, B*
XFD61:	; LD IYH, C*